-- Create foto_ai_reviews table for AI-powered photo evaluations
-- Date: December 6, 2024
-- Purpose: Store AI evaluation results for installation drop photos

CREATE TABLE IF NOT EXISTS foto_ai_reviews (
  -- Primary key
  dr_number VARCHAR(50) PRIMARY KEY,

  -- Overall evaluation results
  overall_status VARCHAR(10) NOT NULL CHECK (overall_status IN ('PASS', 'FAIL')),
  average_score DECIMAL(4,2) NOT NULL CHECK (average_score >= 0 AND average_score <= 10),
  total_steps INTEGER NOT NULL DEFAULT 12,
  passed_steps INTEGER NOT NULL CHECK (passed_steps >= 0 AND passed_steps <= total_steps),

  -- Detailed step results (JSONB for flexibility)
  step_results JSONB NOT NULL,

  -- Markdown report (optional, generated by Python backend)
  markdown_report TEXT,

  -- Feedback tracking
  feedback_sent BOOLEAN NOT NULL DEFAULT FALSE,
  feedback_sent_at TIMESTAMP,

  -- Timestamps
  evaluation_date TIMESTAMP NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create index on evaluation_date for faster queries
CREATE INDEX IF NOT EXISTS idx_foto_ai_reviews_evaluation_date
ON foto_ai_reviews(evaluation_date DESC);

-- Create index on feedback_sent for filtering
CREATE INDEX IF NOT EXISTS idx_foto_ai_reviews_feedback_sent
ON foto_ai_reviews(feedback_sent);

-- Create index on overall_status for filtering
CREATE INDEX IF NOT EXISTS idx_foto_ai_reviews_status
ON foto_ai_reviews(overall_status);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_foto_ai_reviews_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER foto_ai_reviews_updated_at_trigger
BEFORE UPDATE ON foto_ai_reviews
FOR EACH ROW
EXECUTE FUNCTION update_foto_ai_reviews_updated_at();

-- Add comment to table
COMMENT ON TABLE foto_ai_reviews IS 'AI-powered photo evaluations for installation drops';
COMMENT ON COLUMN foto_ai_reviews.dr_number IS 'Drop record number (unique identifier)';
COMMENT ON COLUMN foto_ai_reviews.step_results IS 'JSON array of individual step evaluation results';
COMMENT ON COLUMN foto_ai_reviews.feedback_sent IS 'Whether WhatsApp feedback has been sent';
